### ISSUE TITLE
Add split-bar class / attribute that indicates state

### ISSUE THREAD

**Issue by KevinTCoughlin** [angular-ui/ui-layout#201]
I'm looking to style ui-layout's split-bar while it is being dragged and had some questions.
- Is there currently a mechanism for targeting the split-bar in a certain state?
- If not would it be beneficial to anyone else to add a class or attribute to indicate the split-bar's state? 

I'll gladly implement this feature if there is interest / a need aside from my own.

**Comment by inju-song** [comment]
@KevinTCoughlin 
I need to add split-bar class / attribute too, but this feature is not available in current version. 
In my source, split-bar had to have element such as icon, text.
So I tried to find different approach for the feature, I used pseudo elements(:before, :after) in CSS.

In css of my ui-splitbar,
```css
.ui-splitbar{
        . . .
        /*some css style*/
        . . .
}
```

I added ':after' below the ui-splitbar css.
```css
.ui-splitbar:after {
        font-family: FontAwesome;
        display: block;
        content:"\f0dc some text"; // "\f0dc" is content code of font-awesome
}
```

After compile, after tag is generated beneath the ui-splitbar div and appeared icon, text in split-bar. 

It is trick, but I hope that this approach is of help to you and others who have same trouble.
